name: Auto-Deploy Flask App

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        working-directory: /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver

      - name: Start Flask App
        run: |
          nohup python app.py &
        working-directory: /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver

      - name: Output Deployment URL
        run: echo "App deployed at http://your-server-ip:5000" | tee url.txt
        working-directory: /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver
