name: Auto-Deploy Flask App

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          nohup python app.py > flask.log 2>&1 &


      - name: Output Deployment URL
        run: |
          cd /home/githubrunner/actions-runner/_work/Maze-Solver/Maze-Solver
          echo "App deployed" | tee url.txt
